# This is a basic workflow to help you get started with Actions

name: PHPStan

# Controls when the action will run. 
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  phpstan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Startup
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Run PHPStan
        uses: nxtlvlsoftware/pmmp-phpstan-action@3
        with:
          phpstan-config: phpstan.neon.dist